export const movieListJSON = [
  {id:1, title: 'Die Hard', fresh: true, rating: '95%', gross: '$52,000 '},
  {id:2, title: 'Inception', fresh: false, rating: '92%', gross: '$12,000 '},
  {id:3, title: 'Pirate of Caribbean', fresh: false, rating: '85%', gross: '$32,000 '},
  {id:4, title: 'Avengers: Endgame', fresh: true, rating: '84%', gross: '$42,000 '},
  {id:5, title: 'Star Wars: The Last Jedi', fresh: false, rating: '65%', gross: '$15,000 '},
  {id:6, title: 'Mission Impossible - Ghost Protocol', fresh: false, rating: '65%', gross: '$42,000 '},
  {id:7, title: 'Matrix', fresh: true, rating: '87%', gross: '$9,000 '},
];

export const movieDetailsJSON = {
  1: {
    title: 'Die Hard',
    rating: '95%',
    fresh: true,
    audience: '81%',
    consensus: 'Its many imitators (and sequels) have never come close to matching the taut thrills of the definitive holiday action classic.',
    poster: '/img/die_hard.jpg',
  },
  2: {
    title: 'Inception',
    rating: '92%',
    fresh: false,
    audience: '91%',
    consensus: 'Smart, innovative, and thrilling, Inception is that rare summer blockbuster that succeeds viscerally as well as intellectually.',
    poster: '/img/inception.jpg',
  },
  3: {
    title: 'Pirates of the Caribbean',
    rating: '92%',
    fresh: false,
    audience: '86%',
    consensus: 'May leave you exhausted like the theme park ride that inspired it; however, you\'ll have a good time when it\'s over.',
    poster: '/img/pirates_of_the_caribbean.jpg',
  },
  4: {
    title: 'Avengers: Endgame',
    rating: '92%',
    fresh: true,
    audience: '90%',
    consensus: 'Exciting, entertaining, and emotionally impactful, Avengers: Endgame does whatever it takes to deliver a satisfying finale to Marvel\'s epic Infinity Saga.',
    poster: '/img/endgame.jpg',
  },
  5: {
    title: 'Star Wars: The Last Jedi',
    rating: '92%',
    fresh: false,
    audience: '43%',
    consensus: 'The Last Jedi honors the saga\'s rich legacy while adding some surprising twists -- and delivering all the emotion-rich action fans could hope for.',
    poster: '/img/last_jedi.jpg',
  },
  6: {
    title: 'Mission Impossible',
    rating: '92%',
    fresh: false,
    audience: '76%',
    consensus: 'Stylish, fast-paced, and loaded with gripping set pieces, the fourth Mission: Impossible is big-budget popcorn entertainment that really works.',
    poster: '/img/ghost_protocol.jpg',
  },
  7: {
    title: 'The Matrix',
    rating: '92%',
    fresh: true,
    audience: '85%',
    consensus: 'Thanks to the Wachowskis\' imaginative vision, The Matrix is a smartly crafted combination of spectacular action and groundbreaking special effects.',
    poster: '/img/matrix.jpg',
  },
};

export const movieReviewsJSON = {
  1: [
        {"id":0,"fresh":true,"text":"Die Hard With A Vengeance is better than Die Hard 2, but not as good as the peerless original."}, 
        {"id":1,"fresh":false,"text":"The first 40 minutes of the movie contain the most giddy and intoxicating action scenes you'll find in any cinema this summer."},
        {"id":2,"fresh":true,"text":"This third installment is so loud, fast and full of chases that watching it is like being abandoned on a set of roller coaster tracks. You're definitely not bored, but you're not necessarily pleased."},
        {"id":3,"fresh":true,"text":"While it isn't as insultingly dopey as the first two films in this series, this Die Hard is every bit as violent, obscene and implausible."},
        {"id":4,"fresh":false,"text":"Returning to the fray after missing the first sequel, John McTiernan directs with a gleeful disregard for narrative logic, especially in the closing stages. It's cracking entertainment, though."},
        {"id":5,"fresh":true,"text":"On a pure production level, Die Hard With a Vengeance is first-rate work. Its highly elaborate stunts and explosions are expertly choreographed and executed."},
      ],
  2: [
        {"id":0,"fresh":false,"text":"Overall, the film is one of a kind, a masterpiece and a work of art so to speak. The superior musical score that accompanies the film heightens the suspense and adds to the mystery sequences."}, 
        {"id":1,"fresh":true,"text":"Nolan masterfully weaves all these elements together, creating a second act that is breathtaking, suspenseful and thought-provoking...unfortunately, it takes us a good hour for us to get there."},
        {"id":2,"fresh":true,"text":"Lose yourself in Chris Nolan's dream-world. You may never want to wake up."},
        {"id":3,"fresh":true,"text":"A smart summer thriller filled with visionary set pieces, grand imagery and exciting twists, but its lack of an emotional center keeps it just short of greatness."},
        {"id":4,"fresh":false,"text":"A mind-bending thriller that is a complete original, cementing Nolan's status as one of this generation's brightest filmmakers."},
        {"id":5,"fresh":true,"text":"Imagine watching a bank heist in someone's brain, with layers upon layers upon layers (repeat) of deep meaning, suspense, action, mystery and ohmyf*ckinggod-what-the-HELL-is-happening moments, and you can imagine what it's like to watch Inception."},
     ],
  3: [
        {"id":0,"fresh":false,"text":"There's always too much going on, which is easily forgivable for a while. But as the minutes mount, the flaws are only accentuated."}, 
        {"id":1,"fresh":false,"text":"Ahoy mateys! Shiver me timbers, I think we have a winner here!"}, 
        {"id":2,"fresh":false,"text":"'Pirates of the Caribbean: The Curse of the Black Pearl' remains a rarity among this summer's movies in that it not only meets audience expectations, it exceeds them."},
        {"id":3,"fresh":false,"text":"This is about 45 minutes too long but it still holds up as a rousing old-school adventure movie like you might have gotten with Errol Flynn back in the day."},
        {"id":4,"fresh":true,"text":"Less Douglas Fairbanks than an aquatic Artful Dodger gone to seed, he's a high seas con man with a heart of tarnished stolen gold."},
        {"id":5,"fresh":true,"text":"Rip-roaring fun for kids who don't mind skeletons."},
      ],
  4: [
        {"id":0,"fresh":true,"text":"I'm not naïve enough to suppose that anything I can say here is likely to change anyone's plans about going or not going, so I'll simply say that I enjoyed this silly but thrilling superhero free-for-all."},
        {"id":1,"fresh":false,"text":"You would think they would go back to a time when Thanos was young and vulnerable and off him. They opt for a more intricate approach, which bored me."},
        {"id":2,"fresh":true,"text":"Avengers: Infinity War at least had the good taste to abstain from Jeremy Renner. No such luck in Endgame."},
        {"id":3,"fresh":false,"text":"As expected, the film is carried by the original six Avengers, but it does a remarkable job of bringing virtually every memorable character from all 22 movies back onto the screen. It is a staggering reminder of past and present pleasures."},
        {"id":4,"fresh":true,"text":"Endgame definitively closes a few chapters in the Avengers saga in highly satisfying fashion. It is a tremendously entertaining intergalactic trip."},
        {"id":5,"fresh":true,"text":"It is this part of the story, the human side, to narrow it down to our marginal planet, that holds the movie together for its three-hour run time."},
      ],
  5: [
        {"id":0,"fresh":false,"text":"Go see it on the biggest screen possible and let the little kid in you enjoy every moment of it."},
        {"id":1,"fresh":false,"text":"Overall, this is a profoundly satisfying episode without apparent weak spots (it's a notch disjointed, but nothing unbearable): You'll laugh, cry and be in awe..."},
        {"id":2,"fresh":true,"text":"It is the most visually stunning of the eight Star Wars films, the characters speak with the elegance and wit... and the acting is often outstanding. It is exciting, funny, cute, tense, melancholy, smart, goofy, unexpected, and occasionally profound."},
        {"id":3,"fresh":false,"text":"The structure, at times, is similar to 30-minute episodes of a miniseries event that we're binge watching. And while some of the visual effects and cinematography are stunning, something is lacking overall."},
        {"id":4,"fresh":false,"text":"Johnson unleashed one of the most spectacular visual feats within the Star Wars universe."},
        {"id":5,"fresh":true,"text":"Its heart is in the right place, more so than any of the other sequel films, but the conviction is lacking."},
      ],
  6: [
        {"id":0,"fresh":false,"text":"...non-stop, pulsating action that permeates through every frame."},
        {"id":1,"fresh":true,"text":"The stakes are high in the movie but it's not to dark and still fun at the same time. It's also very fun to watch a Mission Impossible movie where the tech fails them over and over."},
        {"id":2,"fresh":false,"text":"As far as decent popcorn movies go, M:I-GP is a nice entry for 2012 - entertaining and thrilling."},
        {"id":3,"fresh":true,"text":"The story itself plays out unremarkably and is not very memorable, but the action certainly holds the attention..."},
        {"id":4,"fresh":true,"text":"Brad Bird's direction is sharp and targeted as one might expect from one of Pixar's secret weapons, who clearly showed his love and appreciation for spies and intrigue with The Incredibles."},
        {"id":5,"fresh":false,"text":"Big. Bold. Breathtaking. I hope the team chooses to accept another mission."},
      ],
  7: [
        {"id":0,"fresh":true,"text": "The Matrix still stands up as a fiercely exciting and discombobulating futurist drama"},
        {"id":1,"fresh":false,"text": "A technologically stunning movie that furthers the genre and features crowd-pleasing performances to go with the frequent scenes of gunplay and violence."},
        {"id":2,"fresh":true,"text":"The Matrix is an inner-circle sci-fi Hall of Famer, a visual trendsetter, and a cultural touchstone that remains culturally prominent today."},
        {"id":3,"fresh":true,"text":"Neo offers Reeves the perfect combination of Ted Theodore Logan's curiosity and wonder, Johnny Utah's earnestness and the badassedness of Jack Traven."},
        {"id":4,"fresh":false,"text":"Full to the brim with eye-popping effects and \"How'd they do that?\" stuntwork, it yearns to have audiences be utterly enraptured in its created reality."},
        {"id":5,"fresh":true,"text":"...hallucinatory cinema."},
     ],
};
